In [1]:
import os
import shutil
import pandas as pd
import numpy as np 
from datetime import datetime

In [2]:
data = pd.read_csv("../dataset/ADNI/data_cleaned.csv")
list_ptid = list(data["PTID"].unique())
print(len(list_ptid))
data

1431

,RID,PTID,EXAMDATE,DX_bl,AGE,PTGENDER,PTEDUCAT,APOE4,CDRSB,ADAS13,...,PET,DTI,Male,Female,APOE4_0,APOE4_1,APOE4_2,CN,MCI,AD
0,3,011_S_0003,2005-09-12,AD,81.300000,Male,18,1.0,4.5,31.00,...,1,0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,3,011_S_0003,2006-09-12,AD,82.300000,Male,18,1.0,3.5,35.00,...,1,0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,3,011_S_0003,2007-09-12,AD,83.300000,Male,18,1.0,8.0,37.67,...,1,0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,4,022_S_0004,2005-11-08,LMCI,67.500000,Male,10,0.0,1.0,21.33,...,0,0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,4,022_S_0004,2006-11-14,LMCI,68.516438,Male,10,0.0,1.0,22.00,...,0,0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7126,6869,057_S_6869,2022-03-01,AD,79.278082,Male,10,NaN,9.0,25.33,...,0,0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,1.0
7127,6869,057_S_6869,2023-03-07,AD,80.294521,Male,10,NaN,11.0,33.67,...,0,0,1.0,0.0,NaN,NaN,NaN,0.0,0.0,1.0
7128,6889,033_S_6889,2020-10-23,LMCI,67.800000,Male,18,0.0,1.0,25.00,...,1,0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7129,6889,033_S_6889,2021-10-25,LMCI,68.805479,Male,18,0.0,1.5,23.33,...,0,0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7130,6889,033_S_6889,2022-10-12,LMCI,69.769863,Male,18,0.0,1.0,17.33,...,0,0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [3]:
def str2datetime(input):
    return datetime.strptime(input, "%Y-%m-%d")

In [5]:
path_root = "G:/Dataset/ADNI/3_smooth (SPM)"
path2save = "G:/Dataset/ADNI/TrainingData"


for k, ptid in enumerate(list_ptid):
#     if "168_S_6151" != ptid:
#         continue
    print(k, ptid)

    path_ptid = os.path.join(path_root, ptid)
    if not os.path.exists(os.path.join(path2save, ptid)):
        os.mkdir(os.path.join(path2save, ptid))
    
    list_visit_mri = [filename for filename in os.listdir(path_ptid) if "MRI" in filename]
    list_visit_pet = [filename for filename in os.listdir(path_ptid) if "PET" in filename]
    list_visit_dti = [filename for filename in os.listdir(path_ptid) if "DTI" in filename]
    patientInfo = np.array(data[["EXAMDATE", "Month", "AGE", "MRI", "PET", "DTI"]][data["PTID"] == ptid].sort_values(by="Month", ascending=True))
    rid = data[data["PTID"] == ptid].index[0]
    #####
    for idx in range(len(patientInfo)):
        examdate = str2datetime(patientInfo[idx, 0])
        month = patientInfo[idx, 1]
    
        if month == 3:
            continue
#         print(month)

        # MRI
        list_diff_mri = []
        for i, filename in enumerate(list_visit_mri):
            date_collected = str2datetime(filename[-14:-4])
            diff = abs(examdate - date_collected).total_seconds()/60/60/24/30
            if diff <= 3:
                list_diff_mri.append(filename)
        if len(list_diff_mri) > 0:
            print("having MRI at: ", month, list_diff_mri[0])
            shutil.copy(os.path.join(path_ptid, list_diff_mri[0]), os.path.join(path2save, ptid, "visit_{:0>3}_{}.nii".format(month, list_diff_mri[0][25:-15])))
#             if not os.path.isfile(os.path.join(path2save, ptid+"_visit_{:0>3}_{}".format(month, list_diff_mri[0][24:]))):
#                 shutil.copy(os.path.join(path_ptid, list_diff_mri[0]), os.path.join(path2save, ptid+"_visit_{:0>3}_{}".format(month, list_diff_mri[0][24:])))
        ## PET
        list_diff_pet = []
        for i, filename in enumerate(list_visit_pet):
            date_collected = str2datetime(filename[-14:-4])
            diff = abs(examdate - date_collected).total_seconds()/60/60/24/30
            if diff <= 3 or (diff <= 5 and "168_S_6151" == ptid):
                list_diff_pet.append(filename)
        if len(list_diff_pet) > 0:
            print("having PET at: ", month, list_diff_pet)
            for k in range(len(list_diff_pet)):
                shutil.copy(os.path.join(path_ptid, list_diff_pet[k]), os.path.join(path2save, ptid, "visit_{:0>3}_{}.nii".format(month, list_diff_pet[k][25:-15])))
#                 shutil.copy(os.path.join(path_ptid, list_diff_pet[k]), os.path.join(path2save, ptid+"_visit_{:0>3}_{}".format(month, list_diff_pet[k][24:])))
        ### DTI
        list_diff_dti = []
        for i, filename in enumerate(list_visit_dti):
            date_collected = str2datetime(filename[-14:-4])
            diff = abs(examdate - date_collected).total_seconds()/60/60/24/30
            if diff <= 3:
                list_diff_dti.append(filename)

        if len(list_diff_dti) > 0:
            print("having DTI at: ", month, list_diff_dti[:2])
            for k in range(2):
                shutil.copy(os.path.join(path_ptid, list_diff_dti[k]), os.path.join(path2save, ptid, "visit_{:0>3}_{}.nii".format(month, list_diff_dti[k][25:-15])))
#                 shutil.copy(os.path.join(path_ptid, list_diff_dti[k]), os.path.join(path2save, ptid+"_visit_{:0>3}_{}".format(month, list_diff_dti[k][24:])))
    print()

1292 168_S_6151
having PET at:  0 ['sw168_S_6151_Month_000.0_PET_AV45_2018-05-24.nii']
having PET at:  24 ['sw168_S_6151_Month_025.1_PET_AV45_2020-06-15.nii']

###